### ISSUE TITLE
skimdb size

### ISSUE THREAD

**Issue by kustomzone** [nice-registry/all-the-package-repos#1]
Perhaps worth adding a note that skimdb download is ~565 MB. (the counter doesn't indicate % done)

**Comment by zeke** [comment]
Good idea. I just tried it but I can't get it to work. Maybe the couchdb endpoint doesn't return a response header that indicates the filesize?

<img width="921" alt="screen shot 2016-12-05 at 11 01 50 pm" src="https://cloud.githubusercontent.com/assets/2289/20904223/ed57482c-bb3e-11e6-8047-9089565700a2.png">

**Comment by kustomzone** [comment]
I'm new to the registry mirror. Can you remember it working in the past?

(googling i can only find references to Erlang/proxies or the disabled CORS/JSONP from a year ago)

**Comment by zeke** [comment]
> Can you remember it working in the past?

Never tried it. We could just add something like `echo 'downloading the 500MB+ registry file' && curl....`

**Comment by zeke** [comment]
Closing, as we're no longer using skimdb but instead replicate.npmjs.com
