### ISSUE TITLE
Github Actions: Missing npm's token 

### ISSUE THREAD

**Issue by eridal** [nice-registry/all-the-package-repos#14]
The release action is failing due to npm not being able to authenticate the github CI

https://github.com/nice-registry/all-the-package-repos/runs/479033586?check_suite_focus=true#step:4:103

The fix is simple:

1. Create a secret, called `NPM_TOKEN` with a valid npm token

  > Here is more info about how to create a npm token: https://docs.npmjs.com/using-private-packages-in-a-ci-cd-workflow

2. Write to `.npmrc` file:

  ```sh
  echo "//registry.npmjs.org/:_authToken=${secrets.NPM_TOKEN}" > ~/.npmrc
  ```

cc: @zeke

**Comment by zeke** [comment]
Nice catch. Thanks for the writeup. Opened this PR: https://github.com/nice-registry/all-the-package-repos/pull/15
