### ISSUE TITLE
Actions release not working yet

### ISSUE THREAD

**Issue by zeke** [nice-registry/all-the-package-repos#16]
The relevant bit from the last Actions run: https://github.com/nice-registry/all-the-package-repos/runs/481710674

```
npm WARN using --force I sure hope you know what you are doing.
v1.347.0
remote: Invalid username or password.
fatal: Authentication failed for 'https://github.com/nice-registry/all-the-package-repos.git/'
```

cc @eridal

**Comment by eridal** [comment]
@zeke yeah, the `.npmrc` trick did not work, let's try with the `~/.npmrc` (#17)

**Comment by zeke** [comment]
Thanks for https://github.com/nice-registry/all-the-package-repos/pull/17. I just landed it.

**Comment by zeke** [comment]
Looking at the failing output, it appears that the issue is not with npm, but with GitHub:

```
remote: Invalid username or password.
fatal: Authentication failed for 'https://github.com/nice-registry/all-the-package-repos.git/'
```

I think this may be because the GITHUB_TOKEN provided by GitHub Actions is expiring. From https://help.github.com/en/actions/configuring-and-managing-workflows/authenticating-with-the-github_token:

> The installation access token expires after 60 minutes. GitHub fetches a token for each job, before the job begins. ... When a workflow run or its jobs are queued for more than one hour, the token may expire before the job starts.

I will create a PAT (personal access token) and add that to the workflow file.

**Comment by zeke** [comment]
Opened and landed https://github.com/nice-registry/all-the-package-repos/pull/20 🤞

**Comment by eridal** [comment]
> Looking at the failing output, it appears that the issue is not with npm, but with GitHub:

The problem could also be with github, but if what you said is correct then at that point the script should have already published to the npm.
npm WARN using --force I sure hope you know what you are doing.
v1.352.0
remote: Invalid username or password.
fatal: Authentication failed for 'https://github.com/nice-registry/all-the-package-repos.git/'
https://www.npmjs.com/package/all-the-package-repos/v/1.352.0


> ```
> remote: Invalid username or password.
> fatal: Authentication failed for 'https://github.com/nice-registry/all-the-package-repos.git/'
> ```
> 
> I think this may be because the GITHUB_TOKEN provided by GitHub Actions is expiring. From https://help.github.com/en/actions/configuring-and-managing-workflows/authenticating-with-the-github_token:
> 
> > The installation access token expires after 60 minutes. GitHub fetches a token for each job, before the job begins. ... When a workflow run or its jobs are queued for more than one hour, the token may expire before the job starts.
> 
> I will create a PAT (personal access token) and add that to the workflow file.

**Comment by eridal** [comment]
@zeke you are right! The script tries to first publish to github and then publish to npm.

```bash
npm version minor -f -m "update all-the-package-repos to %s"
git push origin master --follow-tags
npm publish
```

ok, that means that once we got the incremental update working it will work just fine, as in theory it will take way less than the github's expiration.. again, in theory.

oh btw you latest attempt also failed :)

**Comment by zeke** [comment]
I haven't yet read through your incremental updates PR https://github.com/nice-registry/all-the-package-repos/pull/19, but I want to point out that a valid `NPM_TOKEN` and `GITHUB_PAT_FROM_ZEKE` are both present in the repo secrets now,. This should hopefully unblock you, and you should be able to update the Actions workflow as needed.

**Comment by eridal** [comment]
@zeke The action had failed again.

I think the problem could be on how the secrets are being passed around.

Could you please create a simple secret, like `FOO=this-is-the-secret`? So then we can add a simpler `echo ${FOO}` to the script and validate that the value is correctly being passed around.
