### ISSUE TITLE
update is getting stuck

### ISSUE THREAD

**Issue by eridal** [nice-registry/all-the-package-repos#24]
Hey @zeke 

The update process is getting stuck for some reason, so it can't read anything and it blocks itself until time, which is 5h. Then 3hs later the next schedule runs and resumes the work.

While this is not really a problem, is not ideal. The process is being stuck trying to read from `_changes` and it receives no data, as it wont print any progress to the log. Here is an example..

```
Sat, 04 Apr 2020 16:04:47 GMT   started: 2020-04-04T16:04:47.988Z
Sat, 04 Apr 2020 16:04:47 GMT }
Sat, 04 Apr 2020 21:04:48 GMT killed!
Sat, 04 Apr 2020 21:04:48 GMT writting changes...
```

Notice in the dates how there are exactly 5hs difference, but during that time there were not a single data read (when it read the first update it prints `applying changes...`)

It will be fine if this was cased by a problematic change (like those that weight +100Mb), as the process is self-healing. It will retry three times to read a change and if continues failing it will decide to move on. It adds the change id to the `"ignored"` key, in the metadata. So far it has ignored 4 changes... so it has to be something else.

My gut tells me that the library that reads from the couchdb has some underlying issue. A few weeks ago I contacted the maintainers to propose a set of fixes that were identified when working on the update and they know that library state and thay have plans to replacing it. Not sure how/if that initiative is still being developed.

What can we try? Reducing the timeout window (currently at 5hs) will certainly increase them.

Anyways, just wanted to write my thoughts about this. This is really minor but the perfectionist in me can't help :)

**Comment by zeke** [comment]
> the library that reads from the couchdb has some underlying issue

Which library is that? Is there an open issue for it?

**Comment by eridal** [comment]
@zeke https://github.com/cloudant-labs/cloudant-follow/issues/141

**Comment by zeke** [comment]
Hey @eridal it looks like things are back on track. Should we close this?

**Comment by eridal** [comment]
Yep, let's close it
