### ISSUE TITLE
Include all packages, even if they don't have repos

### ISSUE THREAD

**Issue by zeke** [nice-registry/all-the-package-repos#30]
The build process for this package currently omits packages that don't have a `repository` field.

What if we changed it to preserve all the packages, and just use `null` values for packages that don't have a repository? Here's an example of what that would look like:

```js
{
  foo: 'https://github.com/someuser/foo',
  bar: 'https://github.com/someuser/bar',
  baz: null
}
```

If we made this change, this package would then implicitly include all the public package names in the npm registry, and it would make the process for updating the [`all-the-package-names`](https://github.com/nice-registry/all-the-package-names) package way easier, without any duplicate npm registry code between the two projects. It would be a matter of updating the `all-the-package-names` build and release process to install `all-the-package-repos` then output `Object.keys(require('all-the-package-repos'))`.

@jimaek what do you think?

**Comment by zeke** [comment]
> It would be a matter of updating the `all-the-package-names` build and release process to install `all-the-package-repos` then output `Object.keys(require('all-the-package-repos'))`.

Alternatively, `all-the-package-names` could be updated to have no build process at all and instead just add `all-the-package-repos` as a dependency.

**Comment by MartinKolarik** [comment]
Considering the version with repos will take a lot more space and memory (at least on load) I think it's worth to prebuild names-only version.

**Comment by zarianec** [comment]
I had some fun playing with `all-the-package-names` and it's definitely not an option to migrate it to GitHub actions "as is". Processing 1.7M million packages on every run takes too much time and it's just a waste of resources 🔥 
To overcome this we must track the latest synchronized sequence from the npm db and that's exactly what package-repos does, so the idea of using the `all-the-package-repos` as a source for package names is great.

The only thing that could break - is the use-case where the package name is explicitly checked for `undefined`

```javascript
if (packageRepos.somePackage !== undefined) { // do something with a repo }
```

**Comment by MartinKolarik** [comment]
@zarianec the repos package should definitely get a new major version IMO if we make that change.

**Comment by zeke** [comment]
cc @eridal who did the semi-recent refactor of the `all-the-package-repos` build process to maintain registry state between Actions runs. ✨

**Comment by eridal** [comment]
Seems like the change is rather simple, we just need to change [this check](https://github.com/nice-registry/all-the-package-repos/blob/59d446bfb5c6a79365106a4ab4434789690b5ea4/scripts/update.js#L224-L229) and the update process will start accepting repos that previously were rejected. 

Luckily we are keeping track of those [invalid changes](https://github.com/nice-registry/all-the-package-repos/blob/59d446bfb5c6a79365106a4ab4434789690b5ea4/data/metadata.json#L25), so far the update collected about 6.1M changes.. but there were 1.9M being invalid That number was way higher than what I expected. 

Also I like the point that zarianec made. Can we talk about what are the implications for those downstream? How can we start including the `null` while being safe for those consuming the package?

**Comment by MartinKolarik** [comment]
> Also I like the point that zarianec made. Can we talk about what are the implications for those downstream? How can we start including the null while being safe for those consuming the package?

We could have the version with null available under something like `require('all-the-package-repos/all')` and keep the default export null-free by changing it to JS which loads the list, filters it, and reexports. But I think it's better to just release a new major version of this package and mark adding `null` as a breaking change.

**Comment by zarianec** [comment]
I just opened a PR where all the packages are listed even without repositories. At that point, it was created assuming we are going to release a new major version with breaking changes.

Also, few other things were refactored and/or deleted.

**Comment by zarianec** [comment]
We really need to get the all-the-package-names working so let's conclude what we are going to do with it.

Two possible ways were mentioned:

1. publish the new major version and mark null values as a breaking change
2. start including the `null` in the packages.json but set the default import to a script where we filter `null` values

IMO the new major version should work just fine and the changes that must be done in order to migrate are pretty simple.

@zeke @eridal what do you think about it?

**Comment by zeke** [comment]
> 1. publish the new major version and mark null values as a breaking change

This option sounds good to me. 👍🏼  I'll review https://github.com/nice-registry/all-the-package-repos/pull/31 now...

**Comment by zeke** [comment]
Left some feedback on #31. TLDR: Great start but I think it needs to be whittled down.
