### ISSUE TITLE
Unable to unpublish a package

### ISSUE THREAD

**Issue by jdkgabri** [nice-registry/all-the-package-repos#48]
I want to unpublish a public npm pacakge that I created few days ago just for ivestigation purposes: https://www.npmjs.com/package/plugin-nakama

Eventually I am not going to need it. The package does not have any downloads in the last week and I am the only maintainer, however, it has one single dependancy: @everything-registry/sub-chunk-2448

I believe that @everything-registry includes its dependancy because of this repo, as it depends on all-the-package-names, which depends on all-the-package-repos.

Could we please stop making  @everything-registry/sub-chunk-2448 dependant on my package, maybe excluding it from this list in this repo/package, so I can try to unpublish it?

Thanks

**Comment by MartinKolarik** [comment]
Hey, our packages are just data files, we don't set the listed packages as dependencies here.
